In [1]:
from elasticsearch import Elasticsearch, helpers
import json
import pandas as pd


from elasticsearch import Elasticsearch

es = Elasticsearch("http://localhost:9200", http_auth=("elastic", "OsboUfs5GKauVaoV5=dQ"))

C:\Users\Hrithik\AppData\Local\Temp\ipykernel_15072\3980900022.py:8: DeprecationWarning: The 'http_auth' parameter is deprecated. Use 'basic_auth' or 'bearer_auth' parameters instead
  es = Elasticsearch("http://localhost:9200", http_auth=("elastic", "OsboUfs5GKauVaoV5=dQ"))

In [2]:
df = pd.read_csv('salary_survey-1.csv')

In [3]:
df.isna().sum()

Timestamp                                                                       0
How old are you?                                                                0
What industry do you work in?                                                 970
Job title                                                                       2
What is your annual salary?                                                     3
Please indicate the currency                                                    0
Where are you located? (City/state/country)                                  1775
How many years of post-college professional work experience do you have?        0
If your job title needs additional context, please clarify here:            26709
If "Other," please indicate the currency here:                              34090
dtype: int64

In [4]:
df = df.dropna()

In [5]:
df.isna().sum()

Timestamp                                                                   0
How old are you?                                                            0
What industry do you work in?                                               0
Job title                                                                   0
What is your annual salary?                                                 0
Please indicate the currency                                                0
Where are you located? (City/state/country)                                 0
How many years of post-college professional work experience do you have?    0
If your job title needs additional context, please clarify here:            0
If "Other," please indicate the currency here:                              0
dtype: int64

In [6]:
import re
def clean_salary(salary):
    # Remove non-numeric characters and commas
    salary = re.sub(r'[^\d]', '', str(salary))
    try:
        return float(salary)
    except ValueError:
        return None
df['What is your annual salary?'] = df['What is your annual salary?'].apply(clean_salary)

In [7]:
df = df.dropna()

In [8]:
df.columns

Index(['Timestamp', 'How old are you?', 'What industry do you work in?',
       'Job title', 'What is your annual salary?',
       'Please indicate the currency',
       'Where are you located? (City/state/country)',
       'How many years of post-college professional work experience do you have?',
       'If your job title needs additional context, please clarify here:',
       'If "Other," please indicate the currency here: '],
      dtype='object')

In [9]:
from geopy.geocoders import Nominatim
import pandas as pd

# Initialize the geolocator
geolocator = Nominatim(user_agent="geoapiExercises")

def get_city_from_location(location):
    try:
        location_info = geolocator.geocode(location, exactly_one=True, addressdetails=True)
        city = location_info.raw.get('address', {}).get('city')
        return city
    except Exception as e:
        print(f"Error processing location '{location}': {e}")
        return None

# Apply the function to the "Location" column and update it
df['Where are you located? (City/state/country)'] = df['Where are you located? (City/state/country)'].apply(get_city_from_location)

Error processing location 'Hamilton BDA': 'NoneType' object has no attribute 'raw'
Error processing location 'Arschwalde, bei Zittern, hinterm Mond': 'NoneType' object has no attribute 'raw'
Error processing location 'Bellevue Washingto USA': 'NoneType' object has no attribute 'raw'
Error processing location 'Aldan/PS/USA': 'NoneType' object has no attribute 'raw'
Error processing location 'fdsdafd': 'NoneType' object has no attribute 'raw'

In [10]:
pd.set_option('display.max_rows', None)
df

,Timestamp,How old are you?,What industry do you work in?,Job title,What is your annual salary?,Please indicate the currency,Where are you located? (City/state/country),How many years of post-college professional work experience do you have?,"If your job title needs additional context, please clarify here:","If ""Other,"" please indicate the currency here:"
157,4/24/2019 11:46:04,25-34,Manufacturing,Human Resources Generalist/Payroll Admin,6090.0,USD,Tampa,5-7 years,"Additional hats as required for safety, minist...",Includes monthly incentive pay which can doubl...
1196,4/24/2019 12:07:31,35-44,software development,products engineer,1200000.0,Other,None,8 - 10 years,I develop an in-house CMS and other software p...,CLP
1424,4/24/2019 12:13:09,25-34,Computer consulting and research,Office Manager,720008.0,USD,San Francisco,8 - 10 years,I’m HR/Accounting/Administration (small company),Company also pays 100% health insurance ($600/...
2053,4/24/2019 12:28:44,55-64,Government/Diplomatic,Administrative Assistant/Secretary,34800.0,Other,None,31 - 40 years,Accounting Department,XCD
2096,4/24/2019 12:29:56,25-34,Investment,HR Generalist,65000.0,USD,Denver,5-7 years,-,-
2226,4/24/2019 12:34:13,18-24,Healthcare,Healthcare Assistant,17652.0,GBP,None,1 year or less,roughly equivalent to a CNA in the usa,This is base salary; i receive an extra 44% on...
4507,4/25/2019 0:05:52,25-34,Public Service,Sub-Editor of the Official Report,193000.0,Other,None,5-7 years,I work in the Hansard unit of my country editi...,Trinidad and Tobago Dollar
5368,4/25/2019 0:20:09,25-34,Real Estate Private Equity,Analyst,110000.0,USD,Chicago,5-7 years,Acquisitions,No line for Commission/Bonus
5615,4/25/2019 0:25:16,45-54,Personal Services,Special Needs Attendant (adult),43000.0,USD,Houston,21 - 30 years,"work in client homes, significant overtime",US
5865,4/25/2019 0:29:44,65 or over,Esports,prOfEssSioNal ApEx ELegenaDS PLaYEr,100000000.0,ZAR,None,41 years or more,yOTe,other
6315,4/25/2019 0:36:38,35-44,Finance,Research Assistant,75.0,Other,None,11 - 20 years,Also EA to Csuite execs,BMD - Bermuda dollar
6497,4/25/2019 0:40:06,25-34,Software,Platform tech lead,5300000.0,Other,Ciudad de México,2 - 4 years,Software developer with some leadership respon...,MXN
6682,4/24/2019 13:57:33,25-34,e-commerce,e-commerce specialist,92400.0,Other,Warszawa,8 - 10 years,I translate 99% of the time,Polish Zloty
6922,4/24/2019 14:11:42,25-34,Legal,Business Developer,37764.0,USD,Buffalo,2 - 4 years,"As well as business development, I also fulfil...","$37,764.00"
7529,4/24/2019 14:52:55,35-44,Psychology,Licensed Clinical Psychologist,55000.0,USD,Jacksonville,8 - 10 years,Self-employed in a solo private practice (move...,*Note that my salary has fluctuated bc of chan...
7656,4/24/2019 15:02:07,45-54,Software,Staff Programmer,206500.0,CAD,Toronto,21 - 30 years,"(What I would consider ""Senior"", but the compa...",(Including bonuses. We don't get stock options.)
8023,4/24/2019 15:31:56,35-44,Internet Software,Products Engineer,14640000.0,Other,None,8 - 10 years,I develop an in-house CMS and other software,CLP
8334,4/24/2019 16:00:33,25-34,Telecom,Project Coordinator,4920000.0,Other,None,2 - 4 years,of a team of Technical Writers,HUF
8639,4/24/2019 16:30:35,25-34,Advertising,VP of Employee Experience,13500000.0,USD,Chicago,8 - 10 years,"M&A communications, cultural transformations, ...",5-8% bonus annually
9158,4/24/2019 17:38:41,25-34,Professional Services,Administrative,300000.0,Other,None,2 - 4 years,Typist,Argentinian Pesos
9801,4/24/2019 19:34:47,25-34,Banking and Finance,Customer Service Consultant,51000.0,AUD/NZD,Melbourne,8 - 10 years,Stakeholder relationship management disguised ...,"Uh, AUD and NZD are pretty different. I’m AUD."
9910,4/24/2019 19:56:28,25-34,Education,Native English teacher,2500000.0,Other,창원시,5-7 years,English teacher in public school in Korea,korean Won
10139,4/24/2019 20:50:02,35-44,Media,Freelance journalist,6500000.0,AUD/NZD,None,11 - 20 years,"Editor, writer, proofreader for print publishi...",NZD is not the same as AUD - I'm in NZD
10436,4/24/2019 21:57:41,25-34,Tourism (Museums),Tourism Officer III,480000.0,Other,None,5-7 years,I'm the supervisor for the section that handle...,PHP
10760,4/24/2019 23:25:44,18-24,IT,Support Executive,24000.0,Other,Singapore,2 - 4 years,Providing training and support to customers wh...,SGD
10836,4/25/2019 0:03:06,45-54,Private Education company,Director of Academic Operations,90000000.0,Other,Daerah Khusus Ibukota Jakarta,11 - 20 years,"Sr. Management, National level",IDR
10923,4/25/2019 0:45:34,25-34,Heavy Equipment,Senior Associate Design Engineer,89000.0,USD,Peoria,8 - 10 years,Responsible for design & new product developme...,"Health, vision, dental benefits, 6% 401k match..."
10979,4/25/2019 1:20:41,25-34,Marketing,Copywriter,252000.0,Other,دهستان آبش احمد,2 - 4 years,Copy editor,QAR
11018,4/25/2019 1:55:49,25-34,Library,Assistant Librarian,50000.0,Other,Singapore,5-7 years,Equal to a Manager with 2-3 direct reports,SGD
11024,4/25/2019 2:02:59,25-34,Financial services,Associate editor,48000.0,Other,Singapore,2 - 4 years,Basically a copyeditor (with a Literature degr...,SGD
11060,4/25/2019 2:45:32,25-34,Advertising,Copywriter,264000.0,Other,Cape Town,2 - 4 years,I write ads,ZAR
11062,4/25/2019 2:48:11,25-34,Consulting,Managment Consulting Analyst,84000.0,Other,Warszawa,1 year or less,"Listen, I'm still not sure what the hell I'm d...",PLN zloty
11199,4/25/2019 4:54:48,25-34,Tech,Content Manager,85000.0,AUD/NZD,Sydney,8 - 10 years,Copywriting/Content Strategy,PS AUD and NZD are different :)
11218,4/25/2019 5:19:32,25-34,Public administration,Special consultant,571000.0,Other,Oslo,1 year or less,"Statistics, systems management, automation, us...",NOK
11221,4/25/2019 5:21:27,25-34,Buldings - interier goods,bussiness assistant,240000.0,Other,None,5-7 years,"Small company - so logistic, customer care, in...",CZK
11262,4/25/2019 5:55:17,25-34,Education,Analista de Avaliação,30000.0,Other,None,1 year or less,"My work co sister of making, selecting and mou...",Brazilian reais
11265,4/25/2019 5:56:06,25-34,Performing arts,Programming Coodinator,52000.0,AUD/NZD,Adelaide,2 - 4 years,Coordinating one program in a state-wide festival,AUD
11334,4/25/2019 6:53:47,25-34,IT,Test Engineering Software Analyst,556000.0,Other,Hlavní město Praha,2 - 4 years,Senior Software Tester,CZK
12335,4/25/2019 14:31:07,35-44,Medical device & CPR Equipment,Operations Manager,37440.0,USD,San Antonio,21 - 30 years,only an associates degree.,"17,560 in Commission too"
12947,4/25/2019 23:01:59,25-34,Civil Service,Senior Policy Analyst,84000.0,AUD/NZD,Wellington,2 - 4 years,In a Westminster system of government (UK and ...,NZD
13038,4/26/2019 0:49:47,25-34,IT,Global commodity manager,840000.0,Other,Ciudad de México,11 - 20 years,Procurement sourcing,MXN
15158,4/26/2019 16:00:18,25-34,Collections,Administrative wage garnishment,45000.0,USD,None,1 year or less,Verify borrowers employment submit for garnish...,I get commission once a month
15720,4/26/2019 17:17:06,45-54,Technologie,Winkeladvocat,12000.0,Other,None,2 - 4 years,Picking hair out of soup,Hosenknöpfe
15805,4/26/2019 17:27:55,25-34,Human resource,Global payroll rules developer,1300000.0,Other,None,11 - 20 years,Business analyst,Php
15830,4/26/2019 17:29:48,25-34,Finance,Global payroll rules developer,1300000.0,Other,None,11 - 20 years,Business analyst,Php
16950,4/26/2019 20:25:46,25-34,construction,design manager,48000000.0,Other,Bogotá,8 - 10 years,architect,COP
17051,4/26/2019 20:47:06,35-44,Technology,Territory Sales Manager,100000.0,USD,None,8 - 10 years,Inside sales rep (no headcount),"this is my ontrack earning...made 112,000 60/4..."
17052,4/26/2019 20:47:14,25-34,Insurance,Analyst,58200.0,Other,Singapore,2 - 4 years,Employee benefits broking,SGD
17519,4/26/2019 22:24:07,65 or over,Gy,Vb,30.0,EUR,None,41 years or more,Vhh,Ghjh
18045,4/27/2019 0:38:28,25-34,Tech Firm,Financial Analyst,36000.0,Other,Petaling Jaya,1 year or less,Financial Analyst for the work performed by firm,Malaysian Ringgit
18107,4/27/2019 1:02:05,25-34,Non-banking finance and lending,Senior Unit Manager - Marketing,1015000.0,Other,None,8 - 10 years,The marketing department here is divided into ...,Indian Rupee (INR)
18476,4/27/2019 3:00:44,35-44,Thermo ware,Regional Manager,1200000.0,Other,Mumbai Suburban,5-7 years,Sales manager for Asia continent,INR
18599,4/27/2019 5:40:40,35-44,Finance,Vice President,420000.0,Other,Singapore,11 - 20 years,Investment Advisory,SGD
19466,4/27/2019 15:19:07,25-34,Consulting,Senior Consiltant,2000000.0,Other,Bengaluru,2 - 4 years,Strategy research and constinh,INR
19672,4/27/2019 18:35:48,55-64,Internet Consulting,Founder & CEO,80000.0,Other,Sydney,31 - 40 years,I'm the sole owner at a boutique consulting st...,AUD
20757,4/29/2019 0:10:41,25-34,filmaking,filmaker,15.0,USD,City of New York,2 - 4 years,video editor,none
20811,4/29/2019 5:51:44,25-34,HR tech,CEO,2520000.0,Other,København,2 - 4 years,I'm a co-founder,DKK
20829,4/29/2019 7:19:38,25-34,Sales,Pre-sale,120000.0,Other,Київ,2 - 4 years,I'm intern at the moment,UAH
21007,4/29/2019 8:48:51,35-44,Healthcare,Clinical Psychologist/Assistant Professor,135000.0,USD,Indianapolis,11 - 20 years,Large Academic Health Center,Including Productivity Bonus
21200,4/29/2019 9:10:46,35-44,IT,IT,120000.0,USD,Atlanta,2 - 4 years,Systems support,Dollars
23511,4/29/2019 21:46:35,18-24,Tech,Software Development Intern,66000.0,USD,Madison,1 year or less,Summer Internship prior to graduating with a B...,Salary for 11-week internship is annualized to...
23737,4/30/2019 2:38:13,25-34,information Technology,Manager- Human Resources,900000.0,Other,Ahmedabad,5-7 years,HR,Indian Rupees
23746,4/30/2019 3:06:15,25-34,Municipality,Solutions Architect,760000.0,Other,Oslo,8 - 10 years,ICT field,NOK
23767,4/30/2019 4:35:08,25-34,Management Consulting,Consultant,1150000.0,Other,Mumbai Suburban,2 - 4 years,Though leadership for the organization,indian rupee iNR
25011,4/30/2019 18:54:23,45-54,Aviation,Pilot,158350.0,AUD/NZD,Cairns,11 - 20 years,Captain,Aud
25624,5/1/2019 9:59:13,18-24,Financial Tech,Data Researcher I,312000.0,Other,Makati,1 year or less,content analyst for a data mining side of the ...,PHP (Philippine Peso)
25935,5/1/2019 21:26:24,35-44,Telco,Product Manager,39.0,Other,None,11 - 20 years,General Manager,INR
25975,5/2/2019 0:30:16,35-44,Financial services,Senior manager,151000.0,USD,Chicago,11 - 20 years,Product strategy,22000
26255,5/3/2019 0:45:48,35-44,Government,Data Scientist,24000000.0,Other,Santiago,11 - 20 years,I provide Data Science services to governmenta...,CLP
26285,5/3/2019 7:32:42,25-34,academia,researcher (PhD student),46440000.0,Other,None,2 - 4 years,"in Europe, PhD candidates have already obtaine...",Norwegian crowns
26325,5/3/2019 12:08:24,25-34,Legal (Biglaw),Associate Attorney,208000000.0,Other,서울,5-7 years,Midlevel associate attorney at a Biglaw firm,Korean Won
26440,5/3/2019 17:23:56,25-34,Law,Senior IP Counsel,205000.0,AUD/NZD,None,8 - 10 years,"Patent Attorney, in house",NZD
26634,5/5/2019 11:27:11,35-44,Information Technology,Vice President,260000.0,Other,Warszawa,11 - 20 years,"In my company a ""VP"" is just a senior position...",PLN
26766,5/6/2019 21:18:02,25-34,Cruise Ship,Production Manager,65000.0,USD,Hlavní město Praha,8 - 10 years,"glorified light board operator, designer, gene...",estimate includes benefits package and adjuste...
27191,5/10/2019 13:06:40,55-64,INSURANCE,sales,492000.0,USD,Philadelphia,31 - 40 years,commercial lines,"150,000"
27193,5/10/2019 13:06:59,25-34,Aviation,IT Manager,140000.0,Other,Kraków,5-7 years,SAP products,PLN
28814,5/11/2019 9:09:10,18-24,Software Engineering,Software Engineer,840000.0,Other,काठमाडौं,1 year or less,Python Developer,NRP
29220,5/12/2019 23:22:50,35-44,Banking,Work floor,26000.0,USD,None,5-7 years,Lead,$
29237,5/13/2019 5:32:23,45-54,"Internet, E-Commerce, Digital Marketing",Head Digital Marketing,130000.0,Other,Bengaluru,11 - 20 years,"Lot of times, employers look for ""Digital Mar...",Indian Rupee
29672,5/16/2019 9:24:42,35-44,Hi-tech,Backend Developer,336000.0,Other,תל אביב-יפו,5-7 years,PHP/Python Development,ILS
29797,5/19/2019 17:55:15,35-44,Telecommunications,Construction Specialist II,62400.0,USD,None,8 - 10 years,Coordinator Project Management,30$/HR
29811,5/19/2019 22:48:31,45-54,Financial services,Head of research,460000.0,Other,None,21 - 30 years,Stockbroking sell side research,MYR
29856,5/20/2019 18:35:46,35-44,Business Process Outsourcing,Sr. Sales and Operations Manager,90000.0,USD,None,11 - 20 years,I manage sales team for a third party company ...,I get bonuses too.
29917,5/21/2019 13:04:45,55-64,Religious,Senior Pastor,68000.0,USD,Las Vegas,21 - 30 years,Run a church,American
30144,5/25/2019 13:34:00,35-44,Health care,Dentist,14600000.0,USD,San Diego,8 - 10 years,General Dentist,Dollars
30763,6/20/2019 6:31:57,35-44,medical,Anesthesiologist,5000000.0,Other,臺南市,8 - 10 years,Doctor,NTD
31078,7/23/2019 16:09:26,25-34,Technology,Software Engineer,220000000.0,Other,None,2 - 4 years,Full stack,Indian Rupee
31155,8/9/2019 2:31:38,25-34,Manufacturing,Project systems engineer,70000.0,USD,None,5-7 years,Basically project management/process improvement,Also fantastic benefits
31196,8/19/2019 6:55:29,25-34,Consulting,Senior Business Consultant,43056.0,Other,Cluj-Napoca,2 - 4 years,I consult companies in project management and ...,BGN
31727,11/25/2019 9:10:27,35-44,Aviation Airline,Planning Engineering Executive,90000.0,Other,None,11 - 20 years,Senior Executive,MYR
32343,11/25/2019 20:29:33,25-34,ESL,Curriculum Manager,55200000.0,Other,None,5-7 years,Manage and design English programs for primary...,KRW
33536,1/16/2020 0:45:10,25-34,Energy and Renewables,Analyst,450000.0,Other,Bengaluru,5-7 years,Content Strategist and Editor,INR
33670,1/26/2020 6:37:35,35-44,Media,"Regional Director, insight & Analytics",218000.0,Other,Singapore,11 - 20 years,Market Research and Analytics,SGD
34065,5/21/2020 7:11:07,25-34,Non Profit - Citizenship,Sr. Program Manager - Data,780000.0,Other,Bengaluru,8 - 10 years,Data Analyst / Measurement & Evaluation Analyst,INR
34241,9/11/2020 3:10:46,65 or over,ffsdasdf,fsdafds,45435.0,SEK,None,1 year or less,asdffdas,sddfs
34372,12/26/2020 20:07:18,45-54,Governamental,Analist,160000.0,Other,None,11 - 20 years,MP,Real

In [11]:
df2 = df.to_dict('records')

In [12]:
def generator(df2):
    for c, line in enumerate(df2):
        yield {
            '_index': 'myelkfirst',
            '_id': line.get('show_id', None),
            '_source': {
                "Timestamp": line.get("Timestamp", ""),
                "Industry": line.get("What industry do you work in", ""),
                "JobTitle": line.get("Job title", ""),
                "Salary": line.get("What is your annual salary?", ""),
                "Currency": line.get("Please indicate the currency", ""),
                "Location": line.get("Where are you located? (City/state/country)", ""),
                "YearsOfExperience": line.get("How many years of post-college professional work experience do you have?", ""),
                "AdditionalContext": line.get("If your job title needs additional context, please clarify here:", ""),
                "Other": line.get('If "Other," please indicate the currency here', '')
            }
        }

mycustom = generator(df2)

In [13]:
mycustom

In [14]:
next(mycustom)

{'_index': 'myelkfirst',
 '_id': None,
 '_source': {'Timestamp': '4/24/2019 11:46:04',
  'Industry': '',
  'JobTitle': 'Human Resources Generalist/Payroll Admin',
  'Salary': 6090.0,
  'Currency': 'USD',
  'Location': 'Tampa',
  'YearsOfExperience': '5-7 years',
  'AdditionalContext': 'Additional hats as required for safety, ministry, wellness, etc.',
  'Other': ''}}

In [15]:
Settings = {
    'settings': {
        "number_of_shards": 1,
        "number_of_replicas": 0
    },
    "mappings": {
        "properties": {
            "Timestamp": { "type": "text" },
            "Industry": { "type": "keyword" },
            "JobTitle": { "type": "text" },
            "Salary": { "type": "float" },
            "Currency": { "type": "text" },
            "Location": { "type": "keyword" },
            "YearsOfExperience": { "type": "text" },
            "AdditionalContext": { "type": "text" },
            "Other": { "type": "text" }
        }
    }
}

In [16]:
IndexName = ''
my = es.indices.create(index='myelkfirst', ignore=[400,404],body=Settings)

C:\Users\Hrithik\AppData\Local\Temp\ipykernel_15072\2458035385.py:2: DeprecationWarning: Passing transport options in the API method is deprecated. Use 'Elasticsearch.options()' instead.
  my = es.indices.create(index='myelkfirst', ignore=[400,404],body=Settings)

In [17]:
my

ObjectApiResponse({'acknowledged': True, 'shards_acknowledged': True, 'index': 'myelkfirst'})

In [18]:
len(df2)

96

In [19]:
res = es.indices.get_alias(index="*")
for Name in res:
    print(Name)

.kibana_task_manager_8.10.4_001
myelkfirst
data
.slo-observability.sli-v2
.internal.alerts-observability.slo.alerts-default-000001
.kibana_security_session_1
.internal.alerts-observability.apm.alerts-default-000001
.internal.alerts-observability.metrics.alerts-default-000001
.slo-observability.summary-v2.temp
.apm-custom-link
.kibana_ingest_8.10.4_001
.kibana_8.10.4_001
.security-profile-8
.internal.alerts-security.alerts-default-000001
compensation_data_combined
.transform-notifications-000002
.internal.alerts-stack.alerts-default-000001
my-index-000001
.internal.alerts-observability.logs.alerts-default-000001
.internal.alerts-observability.uptime.alerts-default-000001
.transform-internal-007
.apm-agent-configuration
.apm-source-map
.kibana_security_solution_8.10.4_001
.slo-observability.summary-v2
.security-7
.kibana_analytics_8.10.4_001
.kibana-observability-ai-assistant-conversations-000001
books
name
.kibana-observability-ai-assistant-kb-000001
.async-search
.kibana_alerting_cases_8.10.4_001
customer

C:\Users\Hrithik\AppData\Local\Temp\ipykernel_15072\2804286888.py:1: ElasticsearchWarning: this request accesses system indices: [.kibana_task_manager_8.10.4_001, .kibana_security_session_1, .apm-custom-link, .kibana_ingest_8.10.4_001, .kibana_8.10.4_001, .security-profile-8, .transform-internal-007, .apm-agent-configuration, .kibana_security_solution_8.10.4_001, .security-7, .kibana_analytics_8.10.4_001, .async-search, .kibana_alerting_cases_8.10.4_001], but in a future major version, direct access to system indices will be prevented by default
  res = es.indices.get_alias(index="*")

In [20]:
try:
    res = helpers.bulk(es, generator(df2))
    print("Working")
    print("Response: ",res)
except Exception as e:
    print(e)
    pass

Working
Response:  (96, [])